apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello-world-different
spec:
  schedule: "*/1 * * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: hello
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              command:
                - /bin/sh
                - -c
                - date; echo "{{ .Values.message }}"
